### ISSUE TITLE
XML validation spurious message: `value of attribute "type" is invalid; must be equal to "study-group"`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#467] opened 2023-10-30 10:00 UTC
From @taddhar from https://github.com/openitu/X.icd-schemas/issues/4:

When issuing command 'metanorma site generate', metanorma issues the error:

```
Metanorma XML Syntax: (XML Line 000040:71): value of attribute "type" is invalid; must be equal to "study-group", "tsag" or "work-group"
```

I can't see "type" in `sources/document.adoc` but I see `grouptype = study-group`

Is it that the wrong expected attribute is put in `document.adoc` or is it a deeper mismatch?

From @ronaldtse:

The setting of the document attribute is correct as per [documentation](https://www.metanorma.org/author/itu/ref/document-attributes/):
```adoc
:grouptype: study-group
```

**Comment by opoudjis** [comment] 2023-11-10 09:43
group-type  is realised as the attribute `type` of the element /bibdata/ext/editorialgroup/group. The XML validator is not reported the element name, only the attribute name.

The group type attributes however have the following allowed values:

````
       <choice>
          <value>tsag</value>
          <value>study-group</value>
          <value>work-group</value>
        </choice>
````

So need to investigate further.

**Comment by opoudjis** [comment] 2023-11-10 09:50
The issue is not group, but subgroup. The legal values for group, subgroup, and workgroup types, as far as I have been told, are also:

* tsag: TSAG
* study-group: Study Group
* work-group: Working Group of a Study Group

If that is not the case, then someone needs to tell me to change the grammar. The document currently specifies it to be `question`, which the grammar does not allow.

**Comment by ronaldtse** [comment] 2023-11-13 05:35
There is some truth to the reply. However here's the problem.

In documentation, it says:
> For technical reports, group, subgroup, and workgroup correspond to Question, Study Group and Work Group.

And according to ITU-T documentation (https://www.itu.int/dms_pub/itu-t/opb/res/T-RES-T.1-2016-PDF-E.pdf) this is the correct hierarchy.

i.e. Questions are approved then assigned to Study Groups. Study Groups have Working Groups. 

This means that the proper encoding is:

```doc
:group: 15
:grouptype: ???
:subgroup: 17
:subgrouptype: study-group
:groupyearstart: 2022
:groupyearend: 2024
```

The problem is what the `grouptype` should be for Question? Maybe just `question`?

A Question is clearly not a Study Group nor a Working Group.

**Comment by taddhar** [comment] 2023-11-13 08:27
Team I am just back from IETF 118 and I still feel exhausted. I will have a very difficult 3 days this week but will catch up later with ALL the good work I see here (thank you @opoudjis and all), so bare with me. 

However for this one, in fact when I read the sequence, grouptype, if associated to 15 is indeed a Question. 
But when I read further there is something that doesn't work as SG17 contains Questions like question 15. 

The hierarchy is this

United Nations --> ITU --> ITU-T --> Study Group --> Working Party --> Question

There are other branches like:

United Nations --> ITU --> ITU-T --> TSAG --> Working Party --> Rapporteur Group
United Nations --> ITU --> ITU-T --> TSAG --> Focus Group
United Nations --> ITU --> ITU-T --> Study Group --> JCA
United Nations --> ITU --> ITU-T --> Study Group --> Focus Group
United Nations --> ITU --> ITU-T --> Study Group --> JCA
...

So to me 
```
:group: 17
:grouptype: study-group
:subgroup: 15
:subgrouptype: question
```
Hope this helps

**Comment by opoudjis** [comment] 2023-11-13 08:35
The hierarchy doesn't make sense anyway: how is work-group a valid value for the type of subgroup, if subgroups are study groups? And it clearly does not apply given the foregoing.

Questions as organisers of groups, which Ronald has posted, is also not reflected in the organisational presentation of https://www.itu.int/en/ITU-T/studygroups/2022-2024/Pages/default.aspx .

Unless someone can give me a fixed list of categories, it sounds like the sensible approach is to jettison all enums in the grammar for types, and make them free text, with some guidance given in mn-templates-itu and metanorma.org for the range of values. Right now, I don't trust that `tsag` and `study-group` are the only type of top level group.

**Comment by taddhar** [comment] 2024-03-12 17:50
Sorry for the long delay here @opoudjis ... there is no concept of a work group. Indeed you didn't have the right input information. 

So let me re-ask the question in another way. The metanorma concepts of group, work groups, etc. are how you describe any organization? for example what would you have for IETF?

**Comment by opoudjis** [comment] 2024-03-14 09:51
While the description of bibliographic items (including metadata about documents) is mostly uniform, we allow different SDOs in Metanorma to vary in SDO-specific metadata, and that includes the governance of standards. So:

BIPM: committee+, workgroup*, both with an acronym and name, committees with a constrained list.

BSI: agency*, technical-committee+, subcommittee*, workgroup*, secretariat?

ISO and IEC: technical-committee?, subcommittee?, workgroup?, secretariat?

IETF: committee

IHO: (committee | workgroup | commission)+, recursive, each with a name and abbreviation

NIST: committee+

OGC: committee, subcommittee?, workgroup?

**Comment by taddhar** [comment] 2024-03-15 09:12
> Any attempt to conflate Question with editorial committees is a grotesque ontological confusion that will not be featuring in Metanorma. Questions and groups of questions are _assigned_ to Study Groups: T-RES-T.1-2016 1.5.b.iv. They are in a one-to-many relation to study groups, and can at least temporarily be in a many-to-many relation: T-RES-T.1-2016 1.5.b.v.
> 
> They are clearly not themselves study groups. I don't see them listed in https://www.itu.int/en/ITU-T/groups/Pages/default.aspx, and I don't see them having memberships, secretariats, or subgroups. They are subject matter considered by groups, and motivating the constitution of groups (and described by Question documents, as defined in T-RES-T.1-2016 1bis.4):
> 
> > Description of an area of work to be studied, normally leading to the production of one or more new
> > or revised Recommendations.
> 
> They are not groups themselves.
> 
> This is pernicious muddle. So, to get something out the door that isn't muddle, and that aligns to the current corporate practice:
> 
> * There will be groups, subgroups, workgroups. (This reflects existing Metanorma practice e.g. in ISO.)
> * Subgroups are subgroups of groups. Workgroups are subgroups of subgroups.
> * TSAG is a group. Working Parties are subgroups. Rapporteur Groups are workgroups. (I'm unhappy about Working Parties being subgroups not workgroups, and the alternative is to refer to group-level1, group-level2, group-level3.)
> * Study groups are groups. Regional Groups, Working Parties, and JCAs are subgroups.
> * Focus groups are groups.
> * Groups and subgroups and workgroups constitute editorial committees, as the comparable groupings listed above do elsewhere in Metanorma.
> * Questions  are NOT children of subgroups or of groups: they are encoded outside the editorial committee structure, as a distinct element. Including it in the structure really is just going to cause confusion.
> * Questions have names and identifiers
> * Question ids can (presumably) be related to corresponding Question documents (another reason not to conflate them with editorial committees)
>   
>   * There is also the business of questions being continued (from previous years?), which I have not worked out yet: so
>     Q1/17  Security standardization strategy and coordination is described as "Continuation of Question 1/17" on https://www.itu.int/net4/ITU-T/lists/sgstructure.aspx?Group=17&Period=17 --- which I don't understand, since Q1/17 should already mean "Question 1, period 17".
> * The identifiers of groups and questions could be minimised, e.g. 17 instead of SG17, 1 instead of Q1/17, with the rest of the identifier filled in by context. That's minimalist, but I think it is also unsafe, and too prone to error to be worthwhile.
> * The documentation is untenable in its claim that "For technical reports, group, subgroup, and workgroup correspond to Question, Study Group and Work Group." I note for instance from https://www.itu.int/net4/ITU-T/lists/loqr.aspx?Group=17&Period=17 that Study Group SG17, Working Party 1/17 deals with Questions Q1/17 and Q15/17 . @taddhar  was also unable to make that work above. So Group shall no longer correspond with Question.
> 
> So in the foregoing examples, we will have:
> 
> ```
> :group: SG17
> :grouptype: study-group
> :groupyearstart: 2022
> :groupyearend: 2024
> :subgroup: WP 1/17
> :subgrouptype: working-party
> :questionid: Q15/17
> :question: Security for/by emerging technologies including quantum-based security
> ```
> 
> and
> 
> ```
> :group: TSAG
> :grouptype: tsag
> :subgroup: WP1
> :subgrouptype: working-party
> :workgroup: RG-WM
> :workgrouptype: rapporteur-group
> ```
> 
> The acceptable values of grouptype, subgrouptype, workgrouptype become:
> 
> * grouptype: tsag, study-group, focus-group
> * subgrouptype: working-party, regional-group, jca
> * workgrouptype: rapporteur-group
> 
> There may be more values, you will need to let me know what they are.
> 
> Let me know if this is workable, and I'll put it through.

Ok on this one I will be less verbose because 1) I believe I understand what you consider here but 2) I am not the most authoritative person here and you really need someone like Simao, etc. 

At least READ https://www.itu.int/rec/T-REC-A.1-201909-I/en I think it should give you the current rules. 

I believe in my head I use more the term 'entity' than group and this can be quite fractal.

An entity can have a type indeed:
TSAG, Study Group, Focus Group, Adhoc group, Correspondence Group, JCA, Working Party, Working Group, Question, Rapporteur Group, Regional Group, etc.

And they can be combined differently. 

For example a Focus Group can be attached to TSAG OR to a Study Group.

Same for an Adhoc Group or a Correspondence Group and probably a JCA

But I doubt you can have a Working Party or a Question attached to anything else but TSAG or a Study Group.

Again, go firt to the A.1 above so that we can reflect more on what could be the right approach.

**Comment by opoudjis** [comment] 2024-03-15 10:06
This is telling me that groups can nest in an utterly arbitrary set of hierarchies. It is hopeless to use the grammar to enforce hierarchies, so I won't bother: all types of group, as listed in T-REC-A.1, can appear at any of the 3 (?) levels. Questions cut across those levels, and remain a separate attribute.

**Comment by opoudjis** [comment] 2024-03-15 12:40
Have lodged PR in mn-templates-itu. Once you approve it, @ronaldtse , we can proceed with updating all mn-samples-itu documents, to separate out Questions from group/subgroup.

````
:comment: ### The Question that the report belongs under. If there are multiple Questions, they are comma-delimited, and Questions containing commas must be quoted. The Question should be prefixed with its identifier followed by colon.
:question: Q10/17: Identity management and telebiometrics architecture and mechanisms, "Q11/17: Generic technologies (such as Directory, PKI, formal languages, object identifiers) to support secure applications"
:comment: ### The type of top-level editorial group that the report belongs under; by default study-group. Legal values include: tsag, study-group, focus-group, adhoc-group, correspondence-group, joint-coordination-activity, working-party, working-group, rapporteur-group, intersector-rapporteur-group, regional-group
:group-type: study-group
:comment: ### The Study Group (or similar) that the report belongs under, modelled as an editorial group
:group: Study Group XYZ
:comment: ### The standard acronym of the Study Group
:group-acronym: SG-XYZ
:comment: ### Year that the group's study period started
:group-year-start: 2024
:comment: ### Year that the group's study period ended
:group-year-end: 2026
:comment: ### The type of second-level editorial group that the report belongs under. Legal values as for group-type
:subgroup-type: working-party
:comment: ### The second-level editorial group that the report belongs under
:subgroup: Working Party on Widgets
:comment: ### The standard acronym of the second-level editorial group
:subgroup-acronym: WP-W
:comment: ### The type of third-level editorial group that the report belongs under, if present. Legal values as for group-type
:workgroup-type: rapporteur-group
:comment: ### The third-level editorial group that the report belongs under, if present
:workgroup: Rapporteur Group on Widget Rollout
:comment: ### The standard acronym of the thirf-level editorial group, if present
:workgroup-acronym: RG-WR
````

**Comment by taddhar** [comment] 2024-03-16 00:24
> This is telling me that groups can nest in an utterly arbitrary set of hierarchies. It is hopeless to use the grammar to enforce hierarchies, so I won't bother: all types of group, as listed in T-REC-A.1, can appear at any of the 3 (?) levels. Questions cut across those levels, and remain a separate attribute.

I propose we rather invite Simao to this discussion. 

BTW @opoudjis I am in Singapour right now and will be in Brisbane in 10 hours. Then I go to Sydney, Canberra and am in Melbourne on the 27th in the evenning. Leaving the 29th. Just in case.

**Comment by opoudjis** [comment] 2024-03-19 12:16
@taddhar Sorry for radio silence, I'm at Sydney airport flying back at the moment. The 28th is a Thursday night, I see; I don't have any plans, and if you'd like to catch up, happy to! I work in the Central Business District, which is likely where you'll be based near, so if you are free for dinner, we could do that.

**Comment by opoudjis** [comment] 2024-03-19 12:40
I see "All/17" is a question identifier in documents.

... That's disappointing. But "QAll/17" or "All/17" can be entered into `:question:`, without a question title, and will work.

**Comment by taddhar** [comment] 2024-03-20 21:07
> @taddhar Sorry for radio silence, I'm at Sydney airport flying back at the moment. The 28th is a Thursday night, I see; I don't have any plans, and if you'd like to catch up, happy to! I work in the Central Business District, which is likely where you'll be based near, so if you are free for dinner, we could do that.

Hi @opoudjis no worries, I am in Brisbane and it is 16 hours work per day here at IETF 119!

I believe 28th is good to meet with you. I will be at the Sheraton Melbourne Hotel 27 Little Collins St, Melbourne VIC 3000 ... I imagine this is in the Central Business District?

**Comment by taddhar** [comment] 2024-03-20 21:08
And yes, QAll/17 or All/17 or ALL/17, means that the document is for All the entities of SG17

**Comment by opoudjis** [comment] 2024-03-21 01:37
> > @taddhar Sorry for radio silence, I'm at Sydney airport flying back at the moment. The 28th is a Thursday night, I see; I don't have any plans, and if you'd like to catch up, happy to! I work in the Central Business District, which is likely where you'll be based near, so if you are free for dinner, we could do that.
> 
> Hi @opoudjis no worries, I am in Brisbane and it is 16 hours work per day here at IETF 119!
> 
> I believe 28th is good to meet with you. I will be at the Sheraton Melbourne Hotel 27 Little Collins St, Melbourne VIC 3000 ... I imagine this is in the Central Business District?

Yes, 10 minute walk from my work, we'll coordinate.

**Comment by opoudjis** [comment] 2024-03-31 05:57
I'm closing this ticket, it is implemented, and if things need to be revisited, that can be a separate ticket.

**Closed by opoudjis** 2024-03-31 05:57 UTC
Labels: bug
