### ISSUE TITLE
Line break in an equation?

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#104] opened 2019-10-27 19:05 UTC
Is there an option to add a line break on an arbitrary position in an equation?

In G.650 recommendation, equation II-2, line breaks are used before each "=" sign:
![image](https://user-images.githubusercontent.com/55683568/67639827-e9384b00-f8f4-11e9-9584-657da69411ec.png)

**Comment by opoudjis** [comment] 2019-10-29 00:07
This is a painful issue for us:

https://github.com/metanorma/metanorma-standoc/issues/111

The answer is, not yet. (a) Native Asciimath does not support it. Asciidoctor Asciimath does (as `\\`),  but the Asciimath gem does not; (b) The Word MathML to OOXML converter does not support it, so we would need to intervene in the MathML to OOXML  conversion to make it happen, and that is going to be difficult and time consuming. For now, we do not support it, and this ticket is considered a duplicate of the earlier ticket.

**Closed by opoudjis** 2019-10-29 00:07 UTC
Labels: question
