### ISSUE TITLE
Spacing between titles in Summary section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#84] opened 2019-10-19 10:59 UTC
There is a bigger spacing between the title and the subtitle in the Summary section.

![image](https://user-images.githubusercontent.com/55683568/67143855-1f7c2780-f270-11e9-8a6c-807904f7205c.png)

[years-alignment.zip](https://github.com/metanorma/metanorma-itu/files/3746576/years-alignment.zip)

**Comment by opoudjis** [comment] 2019-10-20 23:31
There are different vertical spaces for different documents, because these documents have been done by hand. Wontfix. @ronaldtse Please let ITU know: there will be a uniform amount of space between title and Summary in ITU documents. 

Recall also that this was formatted as a framing table, and that gave us no end of trouble with rendering—and the table was not being used to impose an absolute position on the Summary anyway.

**Comment by ronaldtse** [comment] 2019-10-29 10:38
@opoudjis I've confirmed with ITU that the desired behavior is to "fix the top of the title and fix the top of the summary". Can this be doable?

**Comment by opoudjis** [comment] 2019-10-29 12:47
The top of the title is obviously fixed, it's at the top of the page. 

Not that the source documents fixed the top of the Summary, but yes, it can be fixed by use of frames. Is there a specific distance from the top of the page that ITU want the top of the summary to be placed?

**Comment by opoudjis** [comment] 2019-10-29 22:55
> Is there a specific distance from the top of the page that ITU want the top of the summary to be placed?

I've open three documents, and found 3cm, 6cm, and 8cm.

`*sigh*`

I'll make it 5cm.

**Closed** 2019-10-29 23:18 UTC
