### ISSUE TITLE
Differences in ITU-T Resolution 1 vs. ITU-T recommendations

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#133] opened 2019-11-17 17:58 UTC
Differences in doc-type: resolution, comparing to recommendation:
1. Front page: 
- there should be no "Resolution ITU" at the end of the front page
- there should be no word "Series" before the title
- logo is different
original:
![image](https://user-images.githubusercontent.com/55683568/69011232-ba981800-0968-11ea-855f-809743ab7bc8.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011235-c552ad00-0968-11ea-9492-d335b4febb97.png)

2. Page with title "Resolution 1 – Rules of procedure of the ITU Telecommunication Standardization Sector" (after the front page) shouldn't appear.
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011243-d7345000-0968-11ea-8d3d-0a79b958aef1.png)

3. "NOTE" and "INTELLECTUAL PROPERTY RIGHTS" shouldn't appear, only "FOREWORD".
original:
![image](https://user-images.githubusercontent.com/55683568/69011244-e3b8a880-0968-11ea-8665-42fb7bcd6c1e.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011246-f0d59780-0968-11ea-8356-786e3fee3361.png)

4. Table of Contents shouldn't appear.
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011256-00ed7700-0969-11ea-9a2b-ad34da29e111.png)

5. Footer: resolution T-RES1 uses footer "WTSA-16 – Resolution 1" instead of something in the format "Rec. ITU-T (xy)".
original:
![image](https://user-images.githubusercontent.com/55683568/69011262-0ea2fc80-0969-11ea-9af6-18590049b257.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011264-19f62800-0969-11ea-9691-6ac48237f7a7.png)

6. Generated heading and title are different and there should be a subtitle including footnotes.
original:
![image](https://user-images.githubusercontent.com/55683568/69011291-75281a80-0969-11ea-8b9c-6a865a98f5bf.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011295-7eb18280-0969-11ea-9c90-4ba0fa1fdac9.png)

7. In Resolution, text can start right after the title, without specifying a section. Or this should be formatted as some kind of unnumbered section?
original:
![image](https://user-images.githubusercontent.com/55683568/69011383-144d1200-096a-11ea-85a9-8d043f22c105.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011387-1dd67a00-096a-11ea-973b-c4fc565538d2.png)

8. There are some "bis" sections and bullets. How can they be written in Metanorma?
original:
![image](https://user-images.githubusercontent.com/55683568/69011397-4f4f4580-096a-11ea-8308-6017aebf5265.png)
![image](https://user-images.githubusercontent.com/55683568/69011408-61c97f00-096a-11ea-9423-89690cc1ced0.png)

9. Cross-references are not related to clauses anymore, rather sections, or they don't include names at all, only numbers.
original:
![image](https://user-images.githubusercontent.com/55683568/69011477-f16f2d80-096a-11ea-924a-fd012b5d4966.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011481-f92ed200-096a-11ea-8d41-6596ad075e38.png)
original:
![image](https://user-images.githubusercontent.com/55683568/69011485-11065600-096b-11ea-8e02-4332f6136aee.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011491-1c598180-096b-11ea-8b1e-e151ce6d899d.png)

10. Subsections' content starts in the same row as its number and the font is smaller.
original:
![image](https://user-images.githubusercontent.com/55683568/69011516-6cd0df00-096b-11ea-9b18-3481ff4aa27f.png)
rendered:
![image](https://user-images.githubusercontent.com/55683568/69011521-8e31cb00-096b-11ea-853e-a5bbe4b3dbe6.png)

11. Sections with multiple titles/subtitles are used in resolution, in the form of chapters. 
original:
![image](https://user-images.githubusercontent.com/55683568/69011557-2a5bd200-096c-11ea-9a72-1704d4072ded.png)

Additionally, original appendix looks like this:
![image](https://user-images.githubusercontent.com/55683568/69377570-d83ce880-0cac-11ea-8851-d251e9c4d85b.png)

while rendered appendix looks like this:
![image](https://user-images.githubusercontent.com/55683568/69377606-eab72200-0cac-11ea-9f57-85f55e199084.png)

**Comment by ronaldtse** [comment] 2019-11-22 01:10
@anermina thank you for explaining the differences! The ITU-T Resolution is technically a new document type, so it will take some effort. I've discussed with @opoudjis and we probably will do this slightly later. 

The converted document itself is good for now (i.e. it doesn't need to look perfect), and it will be used to build the "Resolution" document type when the time comes. Thanks!

**Comment by opoudjis** [comment] 2019-11-22 01:18
Some of these, we should argue to ITU for consistency: I don't see a good reason why the logo should randomly switch from having the ITU name to lacking it.

@anermina, how to do bis is a very good question. Right now, you can't with autonumbering, and of couse _bis_ is an acknwoledgement of autonumbering fail --- that you're being forced to interpolate a number. We have introduced some hacks for subsequences of assets ("Example 7c"), and we might do something similar for interpolated numbers... but I'm not enthusiastic at doing so.

**Comment by ronaldtse** [comment] 2019-11-22 03:01
> Some of these, we should argue to ITU for consistency: I don't see a good reason why the logo should randomly switch from having the ITU name to lacking it.

I agree, we shouldn't consider this as an issue.

> @anermina, how to do bis is a very good question. Right now, you can't with autonumbering, and of couse bis is an acknwoledgement of autonumbering fail --- that you're being forced to interpolate a number. We have introduced some hacks for subsequences of assets ("Example 7c"), and we might do something similar for interpolated numbers... but I'm not enthusiastic at doing so.

We might have to do this later on, the practice of tracking changed clause numbers is quite universal.

**Comment by opoudjis** [comment] 2020-03-30 02:13
@ronaldtse Am I reviving this ticket to create ITU Resolutions?

**Comment by opoudjis** [comment] 2020-12-29 12:26
I am.

Bad news, @Intelligent2013, you will need to come up with a different stylesheet for ITU resolutions as well. Let me make some headway on this first.

**Comment by opoudjis** [comment] 2020-12-29 12:45
1.

ITU resolutions are adopted at conferences, and what has been entered as series and series1 is in fact the conference title and place/date range. As it turns out, the place and year of the conference are used later on in the document, separately. So I am adding new attributes, and will use  them for resolutions:

`:conference:`
`:conference-place:`
`:conference-start-date:`
`:conference-end-date:`

I refuse to change the logo.

**Comment by opoudjis** [comment] 2020-12-30 14:04
Done 2, 3, 4

**Comment by opoudjis** [comment] 2020-12-31 11:39
5. Done.

6. In a resolution, "Rev." is inserted only if this resolution updates a previous resolution: cf. https://www.itu.int/pub/T-RES-T.95-2016/en . We know this in a document by either the `:updates:` attribute being populated, or the `:edition:` attribute being populated with other than `1`. We will go with the latter.

The subtitle will be autogenerated. The footnotes to the title (entered on the document title, added for metanorma-un) will be appended to the subtitle. 

I at this time decline to process a custom number for footnotes.

**Comment by opoudjis** [comment] 2020-12-31 14:27
Moreover, "Resolution" needs to be detached from the title.

**Comment by opoudjis** [comment] 2021-01-01 00:30
7. Admonitions before the main body of sections have been implemented with a `beforeclauses=true`, but this is not an admonition, but a boilerplate clause, such as has just been implemented for terms and conditions.

**Comment by opoudjis** [comment] 2021-01-02 11:42
8. I will come back to, but it will be done with a numbersuffix attribute, which suffixes an arbitrary string to the preceding asset's number; e.g. after section 1, `[numbersuffix=bis]` will generate 1bis, and `[numbersuffix=A]` will generate 1A. We need this flexibility for multiple iterations of such interpolations in documents; it is common to see 22A, 22AA, 22AAA in successive iterations. Tempting though it would be to implement _bis, ter, quater_ as a numbering subsequence, matching currently implemented 1a, 1b, 1c, that would not satisfy the generic requirement of arbitrary suffixing, depending on what suffixes have already been used.

The document requires a "bis" on  a list item, although its implementation relies on sidestepping any autonumbering of list items in Word, and manually typing the list items as `_b)_ \t ...`, `_b)bis_ \t ...`. _That I simply will not do_: I am  not going to up-end the implementation of all list items in Word to encode this—not to mention that doing so in HTML with actual lists is in between extremely difficult and impossible.

**Comment by opoudjis** [comment] 2021-01-02 11:45
9. This is the same convention as for ISO: clauses are Section (instead of Clause), subclauses are just numbered. The difference is switching the clause label depending on type.

**Comment by opoudjis** [comment] 2021-01-02 12:18
10. The subsection content is in 11pt, but that means that the default font size for the document is 11pt. I am not going to action that unless confirmed by ITU, because I can't trust that the differences between doctypes in font size are deliberate. @ronaldtse Please query ITU.

Will inject inline-header = true for all title-less clauses in Resolutions.

**Comment by opoudjis** [comment] 2021-01-02 13:42
11. Inserting supertitles as separate centered paragraphs in Presentation XML.

**Comment by opoudjis** [comment] 2021-01-02 14:54
Where I have got up to.

[T-RES-T.1-2016-MSW-E.doc.zip](https://github.com/metanorma/metanorma-itu/files/5760392/T-RES-T.1-2016-MSW-E.doc.zip)

**Comment by opoudjis** [comment] 2021-01-02 15:09
Remaining task is 8, although formatting of section titles may need tuning.

**Comment by opoudjis** [comment] 2021-01-07 11:33
8. Will go instead with "number" attribute, just as has been done for assets. So clause 7.1.0 is numbered with `[number=0]`, and section 1bis as `[number=1bis]`, which needs to be followed by an explicit `[number=2]`.

**Comment by opoudjis** [comment] 2021-01-07 14:02
For ITU, also need xref counter to have a built in roman numeral option

**Comment by opoudjis** [comment] 2021-01-08 05:35
Have *not* updated the following flavours to deal with number override on sections, because of the complexity of their numbering:

* IEC: IEV section numbering is always assumed to be numeric (116-010-02)
* MPFD
* UN

**Comment by opoudjis** [comment] 2021-01-08 06:18
@anermina For review.

[T-RES.zip](https://github.com/metanorma/metanorma-itu/files/5785531/T-RES.zip)

**Comment by anermina** [comment] 2021-01-08 20:55
Review for generated Word doc vs. original Word doc:

1. Resolution number is missing on the front page.

Generated:
![image](https://user-images.githubusercontent.com/55683568/104061724-6d74a680-51f9-11eb-96cf-42aa32f24c41.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/104061747-79f8ff00-51f9-11eb-8762-b08d2ceb39cb.png)

2. Capital vs. small letter "s" in cross-referencing "section"s. Since we've had capital "c" in "Clause"s, I believe we should also have capital "s" in "Section"s.

Generated:
![image](https://user-images.githubusercontent.com/55683568/104061973-de1bc300-51f9-11eb-8f5c-92f29b80290b.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/104061951-d4925b00-51f9-11eb-9ae3-3cdb9392b436.png)

3. Should we italicize `bis`?

Generated:
![image](https://user-images.githubusercontent.com/55683568/104062101-20450480-51fa-11eb-8bb2-e40583f68f4b.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/104062084-158a6f80-51fa-11eb-84ec-2d5474c11326.png)

4. It seems "ITU-T" is not needed in the footer.

Generated:
![image](https://user-images.githubusercontent.com/55683568/104062331-90538a80-51fa-11eb-96b7-e4a922732711.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/104062324-8af64000-51fa-11eb-950b-63d654f847db.png)

**Comment by anermina** [comment] 2021-01-08 21:02
@Intelligent2013  could you please check the comments from the original post? If needed, I can create a new ticket to address all current differences between generated PDF and original Word doc, just please let me know.

Numbering sections and subsections with `bis` (point 8, and taking into account Nick's comments) works properly in PDF.

**Comment by opoudjis** [comment] 2021-01-11 10:08
@Intelligent2013 I am going to create a new ticket for you, and I'll highlight the XML changes.

**Comment by Intelligent2013** [comment] 2021-01-11 10:26
> I am going to create a new ticket for you, and I'll highlight the XML changes.

@opoudjis thank you, it'll be helpful.

**Comment by opoudjis** [comment] 2021-01-11 12:10
This has just missed released, but to my relief, these fixes are easy.

1. Fixed.
2. In fact the original has only lowercase clause, but it does have uppercase Section. Ludicrous inconsistency, but fixed.
3. I am not going to allow the "bis" in Asciidoctor attribute markup to contain italics; I am instead going to detect the likely strings (bis, ter, quater) in Presentation XML, and italicise them on the spot.
4. Fixed.

I've also made the SECTION headings be 14 point.

**Comment by opoudjis** [comment] 2021-01-11 12:27
The HTML output creates a ToC entry for subheadings only where the subheadings exist. So in section 1, only subclause 1.13 has a distinct title, "Voting"; the remainder are just inline numbers. Hence,

<img width="297" alt="Στιγμιότυπο 2021-01-11, 23 26 05" src="https://user-images.githubusercontent.com/1911039/104182367-77e6a880-5464-11eb-8159-460cd3d86dbe.png">

I'm actually not convinced this is an error. I'm not fixing it without explicit guidance otherwise.

**Comment by opoudjis** [comment] 2021-01-11 12:29
I'm happy with where this has got to, and will close this ticket, with the reminder that footnotes and list numbers numbered bis have currently been left as too hard to implement.

[t-res.zip](https://github.com/metanorma/metanorma-itu/files/5795699/t-res.zip)

**Comment by Intelligent2013** [comment] 2021-01-13 18:12
> @Intelligent2013 could you please check the comments from the original post? If needed, I can create a new ticket to address all current differences between generated PDF and original Word doc, just please let me know.

@anermina I've updated ITU xslt, all issues fixed. Here is resulted PDF: [T-RES-T.1-2016-MSW-E.presentation.pdf](https://github.com/metanorma/metanorma-itu/files/5810361/T-RES-T.1-2016-MSW-E.presentation.pdf)
I close this ticket. If there are any issues, please create a new one.

**Closed by Intelligent2013** 2021-01-13 18:12 UTC
Labels: enhancement
